### ISSUE TITLE
[BUG] Missing climate entity with HA 2024.1.0b

### ISSUE THREAD

**Issue by guevara777** [mathieu-mp/homeassistant-intex-spa#73]
## Version of the custom_component
```text
0.2.5rc2
```

## Configuration
```
Configuration via UI
```
## Describe the bug
Since the update to HA 2024.1.0b the climate-entity of this integration is no longer working. All the other entities still work well.

## Debug log

```yaml
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:507
Integration: Klima (documentation, issues)
First occurred: 15:40:02 (1 occurrences)
Last logged: 15:40:02

Error adding entities for domain climate with platform intex_spa
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 333, in capability_attributes
    if ClimateEntityFeature.TARGET_HUMIDITY in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

------

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:368
Integration: Klima (documentation, issues)
First occurred: 15:40:02 (1 occurrences)
Last logged: 15:40:02

Error while setting up intex_spa platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 333, in capability_attributes
    if ClimateEntityFeature.TARGET_HUMIDITY in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

-----

Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 15:39:54 (13 occurrences)
Last logged: 15:40:17

TEMP_CELSIUS was used from intex_spa, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/mathieu-mp/homeassistant-intex-spa/issues
DEVICE_CLASS_TEMPERATURE was used from intex_spa, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please create a bug report at https://github.com/mathieu-mp/homeassistant-intex-spa/issues
TEMP_CELSIUS was used from ble_monitor, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/custom-components/ble_monitor/issues
TEMP_FAHRENHEIT was used from ble_monitor, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/custom-components/ble_monitor/issues
TIME_HOURS was used from powercalc, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.HOURS instead, please create a bug report at https://github.com/bramstroker/homeassistant-powercalc/issues
```

**Comment by guevara777** [comment]
Update: Working again with HA 2024.01.0b3

**Comment by mathieu-mp** [comment]
Thanks for the issue and the update.
